### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by jsamr** [rimiti/react-native-toastify#6]
Quick definitions for anyone interested: 

``` typescript
declare module '@rimiti/react-native-toastify' {
  import { Component } from 'react'
  import { ViewProps, StyleProp } from 'react-native'
  namespace Toast {
    interface ToastProps {
      position?: 'top' | 'center' | 'bottom'
      textStyle?: StyleProp<Text>
      positionValue?: number
      fadeInDuration?: number
      fadeOutDuration?: number
      opacity?: number
      durationShort?: number
      defaultCloseDelay?: number
    }
  }
  class Toast extends Component<Toast.ToastProps & ViewProps> {
    public show(text: string, duration: number): void
  }
  export = Toast
}


```

**Comment by rimiti** [comment]
Thank you @jsamr for your contribution.

Could you create a PR to https://github.com/DefinitelyTyped/DefinitelyTyped with this type definition? It could be very useful for others people. 🚀

**Comment by jsamr** [comment]
@rimiti Yeah I have written a bunch of definitions for many libraries recently, and I am planning to publish those in DT, for those maintainers who don't wish to have an index.d.ts file in this repo.

Tell me whichever you prefer, I can also publish a PR here.

**Comment by jsamr** [comment]
@rimiti OK, it's gonna be done tonight !
